name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get quicklisp version
      id: date
      run: echo "::set-output name=date::$(date -d $(grep http://beta.quicklisp.org 1.0/root/opt/app-root/install.lisp | awk -F'/' '{ print $6 }') +%Y%m%d)"

    - name: Get short git commit hash
      id: hash
      run: echo "::set-output name=hash::${${{ github.sha }}::7}"

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        context: "1.0"
        image: lisp-10-ubi8
        tags: latest ${{ steps.hash.outputs.hash }} ${{ steps.date.outputs.date }} ${{ steps.date.outputs.date }}.${{ env.GITHUB_RUN_NUMBER }}
        dockerfiles: |
          1.0/Dockerfile
        build-args: |
