name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get quicklisp version
      id: date
      run: echo "::set-output name=date::$(date -d $(grep http://beta.quicklisp.org 1.0/root/opt/app-root/install.lisp | awk -F'/' '{ print $6 }') +%Y%m%d)"

    - name: Get short git commit hash
      id: hash
      run: echo "::set-output name=hash::${GITHUB_SHA::7}"

    - name: Get run number
      id: run
      run: echo "::set-output name=run::${GITHUB_RUN_NUMBER}"

    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        context: "1.0"
        image: lisp-10-ubi8
        tags: latest ${{ steps.hash.outputs.hash }} ${{ steps.date.outputs.date }} ${{ steps.date.outputs.date }}.${{ steps.run.outputs.run }}
        dockerfiles: |
          1.0/Dockerfile
        build-args: |

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/containerlisp
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
